.\"
.\" x11\-touchscreen\-calibrator manual page.
.\" Copyright (C) 2013 Shih\-Yuan Lee (FourDollars)
.\"
.\" Process this file with
.\" groff -man -Tutf8 x11-touchscreen-calibrator.1
.\"
.TH X11-TOUCHSCREEN-CALIBRATOR 1 "x11-touchscreen-calibrator" "GPLv3" "General User Manuals"
.SH NAME
x11\-touchscreen\-calibrator \- X Window System's Touchscreen Calibrator
.SH SYNOPSIS
.PP
.B x11\-touchscreen\-calibrator
x11\-touchscreen\-calibrator [\-d]
.SH DESCRIPTION
X11 Touchscreen Calibrator runs as a daemon in the background.
It will detect the touchscreen automatically and adjust the corresponding
Coordinate Transformation Matrix of Touchscreen xinput when the resolution
is changed. It should also support rotation, reflection and different scaling
modes of display output.
.SH OPTIONS
.TP
.I "\-d"
Run as a daemon, i.e. a background process.
.SH SEE ALSO
.IR http://fourdollars.github.io/x11-touchscreen-calibrator/
.SH AUTHOR
Shin\-Yuan Lee (FourDollars) <fourdollars@gmail.com>
